# Generated by Django 3.1.6 on 2022-02-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralHealthProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='search_data',
            name='predict_for',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
